### ISSUE TITLE
Remove Yammer API that doesnt work anymore 

### ISSUE THREAD

**Issue by frankkienl** [fernandezpablo85/scribe-java#460]
It seems the URL has changed.
See:
http://developer.yammer.com/introduction/#gs-authentication
Code:
https://github.com/fernandezpablo85/scribe-java/blob/master/src/main/java/org/scribe/builder/api/YammerApi.java

**Comment by chaitrarao04** [comment]
anybody working on this?

**Comment by fernandezpablo85** [comment]
There's only one person "working" on the library, and that's me. No I haven't changed those 2 urls yet.

(I'm surprised people are pending on this since it should be dead simple to change the urls in your own code)

**Comment by fernandezpablo85** [comment]
Taking a closer look at Yammers OAuth implementation, seems they went from 1.0a to 2.0. The API as it is won't work and needs to be removed.

**Comment by fernandezpablo85** [comment]
https://github.com/fernandezpablo85/scribe-java/commit/a7235c84f4c09a5952aa382944897533b20f3ce6

**Comment by chaitrarao04** [comment]
Thanks. Intended to take a stab at this if noboby else was working.

**Comment by fernandezpablo85** [comment]
No problem, seems somebody contributed a Yammer 2.0 API, check https://github.com/fernandezpablo85/scribe-java/pull/394
