### ISSUE TITLE
equals of Verifier

### ISSUE THREAD

**Issue by randyumi** [fernandezpablo85/scribe-java#509]
`org.scribe.model.Verifer` does not override `java.Object` #equals.
I have some trouble with unit testing with Mockito stabbing.
Any reasons for not overriding equals?

**Comment by fernandezpablo85** [comment]
@randyumi do you want to send a PR for this or shall we close it?

**Comment by randyumi** [comment]
I am sorry for ignore the message.I do not have much time to send PR.
But I think `Verifier` should implement equals because we are perplexed by that behavior and Effective Java says all classes should implement equals and hashCode method.

**Comment by fernandezpablo85** [comment]
I'll leave this open since it's a nice improvement and may pick it up later this week. BTW effective java __does not__ say that all classes should implement equals/hashCode, but that you should implement both or none.
