### ISSUE TITLE
Is there a authentication service for Oauth 2.0 with parameters in post body?

### ISSUE THREAD

**Issue by ahll** [fernandezpablo85/scribe-java#525]
Many networks(Youtube, Soundcloud...) with Oauth 2.0 are required to put parameter in post body when getting a access token, and the default service is to put parameter in query. Thus could we add a new service for this functionality ?

**Comment by MMMarcy** [comment]
Also JIRA Oauth (1.0a) authentication requires parameters in the body.

**Comment by fernandezpablo85** [comment]
Seems a nice improvement. There's no need for a new service we only need to
add a new SignatureType type:

https://github.com/fernandezpablo85/scribe-java/blob/master/src/main/java/org/scribe/model/SignatureType.java

**Comment by MichaelTheriot** [comment]
Also required for Azure.

**Comment by fernandezpablo85** [comment]
Closing (but waiting for the PR)
