### ISSUE TITLE
org.scribe.builder.api.TwitterApi.SSL.class does not exist in scribe-1.3.6.jar

### ISSUE THREAD

**Issue by edtguy** [fernandezpablo85/scribe-java#534]
I updated scribe in my maven pom file from 1.3.5 to 1.3.6
Now the build fails because org.scribe.builder.api.TwitterApi.SSL.class is not found.
Please advise how to remedy this.

**Comment by fernandezpablo85** [comment]
Just use `TwitterApi.class`
