### ISSUE TITLE
Canceling network calls

### ISSUE THREAD

**Issue by Psest328** [fernandezpablo85/scribe-java#537]
Hopefully this isn't a major sign of my inexperience, but how can I cancel the request/response network calls should the background thread I'm placing the library calls in need to interrupt for any reason (such as the user backing out of the current fragment or exiting the app)?

**Comment by fernandezpablo85** [comment]
java.net.http calls are blocking so the scribe thread "halts" until a response comes out.

You can interrupt that thread and it might just work (if java.net.http is checking the thread interrupted state, you may wanna check the jdk sources)
