### ISSUE TITLE
Scanner keep producing NoSuchElementException for connecting to Yahoo

### ISSUE THREAD

**Issue by barrybear** [fernandezpablo85/scribe-java#540]
Hello there, I am attempting to use your library to connect to Yahoo's API. In my Android project, I am using gradle build and using this link: <b>compile 'org.scribe:scribe:1.3.7'</b>. I imitate the Yahoo example found as closely as possible, almost to a 100%. However, during Verification, scanner.nextLine() produces the exception: NoSuchElementException everytime. And when I attempt to view the Authorization URL in the browser, I'll be seeing this error:

<i>Cycle Prohibited</i>

<i>Description: Could not process your request for the document because it would cause an HTTP proxy cycle. Please check the URL and your browser's proxy settings.</i>

After a couple of refreshes, the screen proceeds to the Authorising access as it should. Is there an issue in my code or in Yahoo's side?

Thanks for your attention..

**Comment by fernandezpablo85** [comment]
It's kinda weird.

If it **eventually** works (at least once) it seems the signature is indeed valid and scribe has done it's job, signing a request is 99% deterministic (the only exception being getting a timestamp and a nonce for OAuth requirements) so if it worked once it should work every time.

You may wanna check with Yahoo! developers or see if other people encountered the same issues.
