### ISSUE TITLE
JiraApi submission

### ISSUE THREAD

**Issue by guy-rouillier** [fernandezpablo85/scribe-java#541]
Thanks for a fine OAuth library.  I was up and running in a very short amount of time.  I'm using it to connect to Jira using OAuth.  I created a customer JiraApi class.  You are free to use it if you wish.

```
package org.scribe.builder.api;

import java.security.KeyFactory;
import java.security.PrivateKey;
import java.security.spec.PKCS8EncodedKeySpec;

import javax.xml.bind.DatatypeConverter;

import org.scribe.builder.api.DefaultApi10a;
import org.scribe.model.Token;
import org.scribe.services.RSASha1SignatureService;
import org.scribe.services.SignatureService;

public class JiraApi extends DefaultApi10a {
  private static final String SERVLET_BASE_URL = "/plugins/servlet";

  private static final String AUTHORIZE_URL = "/oauth/authorize?oauth_token=%s";

  private static final String REQUEST_TOKEN_RESOURCE = "/oauth/request-token";

  private static final String ACCESS_TOKEN_RESOURCE = "/oauth/access-token";

  private String serverBaseUrl = null;

  private String privateKey = null;

  public JiraApi(String serverBaseUrl, String privateKey) {
    this.serverBaseUrl = serverBaseUrl;
    this.privateKey = privateKey;
  }

  @Override
  public String getAccessTokenEndpoint() {
    if (null == serverBaseUrl || 0 == serverBaseUrl.length()) {
      throw new RuntimeException("serverBaseUrl is not properly initialized");
    }

    return serverBaseUrl + SERVLET_BASE_URL + ACCESS_TOKEN_RESOURCE;
  }

  @Override
  public String getRequestTokenEndpoint() {
    if (null == serverBaseUrl || 0 == serverBaseUrl.length()) {
      throw new RuntimeException("serverBaseUrl is not properly initialized");
    }

    return serverBaseUrl + SERVLET_BASE_URL + REQUEST_TOKEN_RESOURCE;
  }

  @Override
  public String getAuthorizationUrl(Token requestToken) {
    if (null == serverBaseUrl || 0 == serverBaseUrl.length()) {
      throw new RuntimeException("serverBaseUrl is not properly initialized");
    }

    return String.format(serverBaseUrl + SERVLET_BASE_URL + AUTHORIZE_URL, requestToken.getToken());
  }

  @Override
  public SignatureService getSignatureService() {
    if (null == privateKey || 0 == privateKey.length()) {
      throw new RuntimeException("privateKey is not properly initialized");
    }

    try {
      KeyFactory fac = KeyFactory.getInstance("RSA");
      PKCS8EncodedKeySpec privKeySpec = new PKCS8EncodedKeySpec(DatatypeConverter.parseBase64Binary(privateKey));
      PrivateKey privateKey = fac.generatePrivate(privKeySpec);
      return new RSASha1SignatureService(privateKey);
    }
    catch (Exception e) {
      throw new RuntimeException(e);
    }
  }
}

```

**Comment by fernandezpablo85** [comment]
Thanks!

**Comment by guy-rouillier** [comment]
Agree, and after submitting, I read your post about modifying the scope for Scribe.  Perfectly understandable as an almost infinite number of Api classes are possible.  I'm trying to be helpful in case others might want to connect to Jira, and this was the best place I could find for submitting.

Perhaps the Wiki could contain a section to collect submitted Api classes, so that they could all be in one place and hopefully easy to find.

Thanks for all your work in creating and maintaining this fine library.  I appreciate your continued efforts.

**Comment by beders** [comment]
Hmm, how do you use it, guy-rouillier?

`new ServiceBuilder().provider(JiraApi.class)...`  won't work because JiraApi doesn't have a default ctor.

**Comment by guy-rouillier** [comment]
I received an offline question asking how to use this class.  Here's an example:

OAuthService service =  new ServiceBuilder().provider(new JiraApi(jiraServerUrl, privateKey)).apiKey(consumerKey).apiSecret(privateKey).callback(callback).build();

You need to pass the privateKey into JiraApi because Jira requires a specific signature service.  And of course, since there are many possible Jira installations (unlike, say, Facebook), you need to identify the Jira URL you wish to connect to.

**Comment by beders** [comment]
Thank you!

**Comment by highcraze** [comment]
Thanks for this update. I was precisely looking for the same.
I have implemented GET method and its working. How do i implement POST method for creating issue. How do i add JSON to a POST request?. Would be great help if you can put example for POST method for Jira using scribe.

**Comment by guy-rouillier** [comment]
I'd strongly suggest using the Jira Remote Java Client.  You can find a link to JRJC on this Jira REST client page: https://docs.atlassian.com/jira/REST/ondemand/

But if you decide to use the REST APIs yourself, you should be able to use the documentation on that page as a guide.  See "http://example.com:8080/jira/rest/api/2/issue [POST]".  When you click on that link, you'll see the following text:

acceptable request representations:
    application/json [expand] 

Click on the [expand], and you'll see a complete example.  That goes into the request entity (i.e., the body of the request).  Depending on which HTTP client library you use, you instruct the request to use Content Type application/json.
