### ISSUE TITLE
OAuthRequest.getAuthorizationHeader

### ISSUE THREAD

**Issue by guy-rouillier** [fernandezpablo85/scribe-java#542]
I need to get the authorization header of a fully formed request without sending it.  I've got code to do that, but extracting the Authorization header is a little more verbose than I'd like:

```
String authorizationHeader = null;

Map<String, String> headerMap = request.getHeaders();
for (Map.Entry<String, String> entry : headerMap.entrySet()) {
  if (OAuthConstants.HEADER.equalsIgnoreCase(entry.getKey())) {
    authorizationHeader = entry.getValue();
    break;
  }
}
```
In an OAuth scenario, accessing the Authorization header is a fairly common thing to do, so having a dedicated method can probaby be justified.  If not, then the following would be just as good:
```
String authorizationHeader  = request.getHeader(OAuthConstants.HEADER);
```
Thanks.

**Comment by fernandezpablo85** [comment]
```java
String authorizationHeader = request.getHeaders().get(OAuthConstants.HEADER);
```

**Comment by guy-rouillier** [comment]
Well, that's embarrassing :).  Thanks.

**Comment by fernandezpablo85** [comment]
Hey no problem :) to be fair, your version of the code handles case sensitive scenarios, but honestly, 99% of the time headers are properly capitalised.
