### ISSUE TITLE
Rest-assured, Scribe and oauth2 problem

### ISSUE THREAD

**Issue by Artgit** [fernandezpablo85/scribe-java#546]
Hi,

I run into the problem http://stackoverflow.com/questions/29155161/restassured-oauth2-http-status-code-401 using Rest-assured test framework.Seems that this issue related to underlying Scribe functionality under the hood of Rest-assured.

Is there some kind of workaround based on Restassured and Scribe in order to avoid this issue ? Thanks!

**Comment by fernandezpablo85** [comment]
This is not the RestAssured repo.
