### ISSUE TITLE
{"errors":[{"message":"Could not authenticate you","code":32}]}

### ISSUE THREAD

**Issue by DragodApps** [fernandezpablo85/scribe-java#547]
Making a request to Twitter returns the above error code - Even when I properly create an 'Authorization' Header and add it to the request.

My app does the following:
I create a Token using new Token(tokenString, clientSecret);
I create a service: 

		ServiceBuilder servicebuild = new ServiceBuilder()
				.provider(TwitterApi.SSL.class).apiKey(clientId)
				.apiSecret(clientSecret);

Make request:

		 OAuthRequest request = new OAuthRequest(Verb.GET, "https://api.twitter.com/1.1/account/verify_credentials.json");

		service.signRequest(accessToken, request);

		Response response = request.send();

request.send() causes an exception on some devices , as 'Authentication challenge cannot be found' or 'is null'. On other devices, it causes the response to be valid, but return the error code shown in the title.

Do you know what could be causing this? On the occasion that I tried adding an authorization header, I did this:

		request.addHeader("Authorization", headercontents");

and also tried

		service(builder).signatureType(SignatureType.Header)

Cheers for any help

**Comment by fernandezpablo85** [comment]
No idea, have you checked the twitter dev forums for similar errors? I know people have used scribe in android successfully in the past.

**Comment by DragodApps** [comment]
Yes I have checked the twitter dev forums, people have had this error before, however I was not sure if the problem was with Scribe + android somehow.
Do you think there is a possibility the error is due to me creating the access token manually with strings?
Also, does adding the Authorization header add the header in a way which is relevant to this: https://dev.twitter.com/oauth/overview/authorizing-requests

Thanks for your prompt response, you're a lifesaver :P

**Comment by fernandezpablo85** [comment]
I'd try to isolate the issue by running the same code (at least the HTTP calls) on a PC, to rule out a scribe issue. I have heard about different issues on android but I thought we had those covered :/

Anyway, that would help you scope the problem and also make it easier to reproduce (no need to emulate a thing).

**Comment by DragodApps** [comment]
In the end I solved this issue by using Signpost for the https calls to Twitter. I suspect scribe will work fine with other social media sites, however, so I will continue to use Scribe for the other media. One of the few differences between when I used Scribe and when I used Signpost is that I supplied an access token secret to Signpost. I wonder if this was perhaps part of the issue?

Anyway, thank you for your help, and thank you for such a simple and concise library (Has saved me tons of time so far).

**Comment by fernandezpablo85** [comment]
how did you construct the Token object without a token secret?

**Comment by DragodApps** [comment]
I used the Wuman Oauth library for initially authorizing my app. Although in the examples, only a quite high level object (Credential) is shown, a lower form can be obtained called a OAuthHmacCredential. This object had a method which could be used to extract the token secret, which I used to create the Token object. I'm not sure about much more than that - here is some of my code

     // A form of sharedpreferences
     final SharedPreferencesCredentialStore credentialStore = SocialMediaHelperClass
				.getAuthCredentialStore(ctx); 

     // Creating credential with JacksonFactory, etc
		OAuthHmacCredential toBeFilled = SocialMediaHelperClass
				.setFactoryStuffs(providerNumber); 
		try { //Filling the Credential with access token, secret etc...
			credentialStore.load(SocialMediaHelperClass.ACCESS_CRED_STORE_PREFS
					+ providerNumber, toBeFilled);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		consumer.setTokenWithSecret(toBeFilled.getAccessToken(),
				toBeFilled.getTokenSharedSecret());
