### ISSUE TITLE
 Response body is incorrect. Can't extract a token from this

### ISSUE THREAD

**Issue by saschaarthur** [fernandezpablo85/scribe-java#548]
Hello,

i would like to report some trouble with expired FB tokens. It seems it should be handled better but TokenExtractor fails:

heres the line im Calling in java:

String code = request.getParameter("code");
Verifier v = new Verifier(code);
Token accessToken = OAuthHelper.FacebookOAuth.service.getAccessToken(null, v);

Heres the Stacktrace:

Exception:org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract a token from this: '{"error":{"message":"This authorization code has expired.","type":"OAuthException","code":100}}'

org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract a token from this: '{"error":{"message":"This authorization code has expired.","type":"OAuthException","code":100}}'
	at org.scribe.extractors.TokenExtractor20Impl.extract(TokenExtractor20Impl.java:32)
	at org.scribe.oauth.OAuth20ServiceImpl.getAccessToken(OAuth20ServiceImpl.java:37)

Im running maven 1.37

**Comment by fernandezpablo85** [comment]
how would you handle it better?
