### ISSUE TITLE
LinkedIn r_fullprofile not supported

### ISSUE THREAD

**Issue by Wenceslaus** [fernandezpablo85/scribe-java#553]
authService.getRequestToken() return error now:
Response body is incorrect. Can't extract token and secret from this: 'oauth_problem=Scope%20NOT_AUTHORIZED%20%3A%20r_fullprofile'

r_fullprofile is not supported now https://developer.linkedin.com/support/developer-program-transition

Please, fix this.

**Comment by fernandezpablo85** [comment]
pull requests are welcome :smiley: !

**Comment by bogdanRada** [comment]
any updated on this? why was this closed? this is still not supported

**Comment by kullfar** [comment]
possibly, it has been fixed, at least partly. check the new version of ScribeJava

**Comment by bogdanRada** [comment]
ahh nevermind , It seems this is only working if the application is accepted to the Apply with LinkedIn partner program ( https://developer.linkedin.com/support/developer-program-transition ) 

Sorry for the trouble. THank you very much

I love this library :)
