### ISSUE TITLE
I can not get the Turkish characters right.

### ISSUE THREAD

**Issue by ebulanik** [fernandezpablo85/scribe-java#554]
Thanks for the this user friendly library, but I have a small issue with Turkish characters. Although I use UTF-8 coding with InputStreamRreader, I can not get them right from public stream. Here is the code and output. Can you please help me?

![pablo](https://cloud.githubusercontent.com/assets/3069855/7837120/e117a5b6-048d-11e5-8318-c1bd1b4baf96.png)

**Comment by fernandezpablo85** [comment]
what's the encoding of the eclipse terminal? try running it from the
command line and piping the output to a text file, then open that in a text
editor that you know that supports UTF-8 and see if you get scrambled text
again.

**Comment by fernandezpablo85** [comment]
Closing this.
