### ISSUE TITLE
 Converting the request token to an access token

### ISSUE THREAD

**Issue by akoskm** [fernandezpablo85/scribe-java#560]
Hello and thanks for the great library! I already used it for LinkedIn and it was flawless, but I have problem with Twitter sign-in. According to https://dev.twitter.com/web/sign-in/implementing 3:

> To render the request token into a usable access token, your application must make a request to the POST oauth / access_token endpoint, containing the oauth_verifier value obtained in step 2. The request token is also passed in the oauth_token portion of the header, but this will have been added by the signing process.

If I understand correctly, I should be able to get an access token by passing only the `oauth_token` and the `oauth_verifier` to `oaut /access_token` endpoint, however I can't find any way to do this with the current API.

The best I come up with was this:

     OAuthService service = new ServiceBuilder()
                .provider(TwitterApi.class)
                .callback("https://localhost:9090/app/ui/oauth/twitter")
                .apiKey(TWITTER_CONSUMER_KEY)
                .apiSecret(TWITTER_CONSUMER_SECRET)
                .build();

    Verifier verifier = new Verifier(verifierToken);
    Token accessToken = service.getAccessToken(requestToken, verifier);

but `getAccessToken` also requires a token object which I don't have at this moment.

Any idea how I should create it?

**Comment by fernandezpablo85** [comment]
To get an `access token` you first need a `request token`, please check the Twitter example:

https://github.com/fernandezpablo85/scribe-java/blob/master/src/test/java/org/scribe/examples/TwitterExample.java

Also, this is not an issue but a question. Closing it.

**Comment by akoskm** [comment]
Yes, it is more of a question but I haven't found a better place to ask this, sorry!

Yes, I've checked that example and it's a completely different situation from mine. I'm working on a server application and there is a redirect between obtaining a request token and converting that request token (which isn't an object anymore after the redirect but only a combination of `oauth_token` and `oauth_verifier`) to an access token.

Looking at the `public Token(String token, String secret)` API, it wasn't straightforward that I can construct a new Token from the `oauth_token` and the `oauth_verifier` parameters if I supply then as `token` and `secret`. The new token can be passed to `getAccessToken` and it will return an access token.

I don't have any better alternatives regarding the parameter naming of the `Token` constructor, however I think I should write a tutorial which explains how to obtain an access token in server applications.

Thank you for your input!

**Comment by fernandezpablo85** [comment]
> but getAccessToken also requires a token object which I don't have at this moment.

By "I don't have at this moment" do you mean that you generated the `request token`, redirected the user somewhere, got a request back with the verifier and now you have the verifier but forgot to temporarily store the token?

**Comment by akoskm** [comment]
No, I didn't forget to store the token temporarily because according to https://dev.twitter.com/web/sign-in/implementing 3. I don't have to. That's because after redirecting the user, the new location URL will contain the `oauth_token` and the `oauth_verifier` parameters, which are - according to the same documentation - all you need to retrieve an access token. This turned out to be true.

I just wasn't able to figure out from the API how and to which object I have to pass them to make it work.

**Comment by fernandezpablo85** [comment]
You are right, it might be confusing in cases like this, which are not at all uncommon. Do you have any idea of how can we express that clearly in scribe code (besides writing a tutorial, which I'd be delighted to include in scribe's wiki :smile: )

**Comment by akoskm** [comment]
Yes, I was searching for implementation details about such scenarios and I basically found nothing. I'll complete my tutorial soon, but the repository with the demo project is already up here: https://github.com/akoskm/twitter-sign-in-example

Currently I can't propose anything meaningful because the application I'm working on currently handles only Twitter Sign In and this might be a Twitter-only workflow. I'll implement Facebook Sing-in soon so with more information I might be able to identify a workflow which is common for both providers.

**Comment by akoskm** [comment]
As I promised: http://akoskm.github.io/2015/07/31/twitter-sign-in-for-web-apps.html

**Comment by rsparkyc** [comment]
I actually created https://github.com/scribejava/scribejava/issues/581 before realizing you were asking the same question.  I'll be taking a look at the post you made now.
