### ISSUE TITLE
createConnection()  in Request.java  can not be override

### ISSUE THREAD

**Issue by biaotang** [fernandezpablo85/scribe-java#562]
Hi
  Gerrit provides oauth interface, and it use Request . but I  have trouble connecting to an Oauth provider over SSL. 
 so  I  want  to extend the Request class  and  modify it  to accept any certificates,but  i  find  the property  connection   has  no get  method . 
am i  wrong to understand  that how to modify to accept any certificates

Thanks

**Comment by fernandezpablo85** [comment]
scribe uses java.net.http classes, so you can use `trustool` or `TrustManager` as usual.
