### ISSUE TITLE
Maven repo down

### ISSUE THREAD

**Issue by AndrewZurn** [fernandezpablo85/scribe-java#563]
Hey there,

I'm having some trouble connecting to your maven repo, https://raw.github.com/fernandezpablo85/scribe-java/mvn-repo/. Is it potentially down right now?  I'm getting a 400 error when I try to open the page directly in my browser.

Andrew

**Comment by fernandezpablo85** [comment]
400 means Bad Request, not that the server is down.

What are you trying to do?
