### ISSUE TITLE
[Enhancement] Add support for force_login in TwitterAPI

### ISSUE THREAD

**Issue by juliendangers** [fernandezpablo85/scribe-java#564]
It would be great to support the force_login parameter, which allow users with multiple account to choose another one than the one their actually connected with, when authorizing the app. 
Otherwise you need to cancel the request, disconnect your twitter account, reconnect with the desired account, then go through the authorization process again
See https://dev.twitter.com/oauth/reference/get/oauth/authenticate#api-param-force_login

**Comment by fernandezpablo85** [comment]
Can't this be implemented by just extending `TwitterApi` with your custom request token url ?

**Comment by juliendangers** [comment]
yes, that is what we've done so far, just wondering if it could be natively supported

**Comment by fernandezpablo85** [comment]
I don't see the point.
