### ISSUE TITLE
Issue in OAuthEncoder with Flickr API

### ISSUE THREAD

**Issue by adziki** [fernandezpablo85/scribe-java#565]
I've been trying to track down why the Flickr API wasn't working for me, and have boiled it down to the URL Encoding of the "oauth_signature" OAuth parameter.  My generated signature before OAuthEncoder ends with: "ruClvsw%3D".  Once this parameter is encoded https://github.com/fernandezpablo85/scribe-java/blob/a041f626bf959da1da0d5a95eeba37da12c92487/src/main/java/org/scribe/utils/OAuthEncoder.java#L34 the result is "ruClvsw%253D", because "%" when encoded becomes "%25".  

I'm not sure if the encoding (uses HMAC-SHA1 encoding) is supposed to produce the percent sign as a valid output, or if this kind of issue was the intent behind including the ENCODING_RULES set of rules to fix some issues.  Would adding a new rule for "%25" -> "%" fix this?

**Comment by fernandezpablo85** [comment]
Where are you seeing the `ruClvsw%3D` signature? I'm asking because the HMAC-SHA1 signatures usually end in `=` which after percent encoding becomes `%3D`, so I'm thinking the string is somehow getting econded twice.

**Comment by adziki** [comment]
ohhh, interesting.  Let me double check on that and get back to you.

**Comment by adziki** [comment]
ok that seemed to do it, thanks for catching that.  it was getting double encoded :)

**Comment by fernandezpablo85** [comment]
fantastic. closing this one.
